### ISSUE TITLE
Rewrite in Go

### ISSUE THREAD

**Issue by knazarov** [tarantool/cartridge-cli#106]
I believe it's time to rewrite this utility in Go. It has great value for end-user and building it completely static will help making it relatively platform-independent and remove a lot of quirks in making it compatible across enterprise and community editions (by not requiring a runtime).

In addition, I'd like cartridge-cli to be used as a part of application and rock building and publishing flow.

Plus, rewriting it in Go will allow to incorporate process management and basic monitoring.

**Comment by bm0** [comment]
Henlo colleagues. I just started rewriting it for fun.
Creating a new project based on the template has already been implemented.
Project templates are passed through the code generator before compile, with the result that we get a single executable file with no dependencies . I've also sketched out other commands, but so far it's nothing more than a structure.

Let's discuss? Are you interested?
I would gladly contribute to your project.

**Comment by knazarov** [comment]
@bm0 Sure, we may collaborate on it. Right now the most pressing problem is porting rpm and deb packaging, as they are fragile and error prone. We have a test suite for current cartridge-cli, and expect it to work on the new cartridge-cli version as well.
