### ISSUE TITLE
Speed up tests

### ISSUE THREAD

**Issue by dokshina** [tarantool/cartridge-cli#109]
Now python tests are run for about 45 minutes. It's too long.

The main reason for increasing test time is that now tests are run for both original and deprecated project structures. 
I sure that we can't stop testing deprecated flow, moreover, maybe we should start testing different cartridge versions.

Now there are many cases not covered by tests, so the tests count should be increased more.

**Comment by olegrok** [comment]
I suggest to consider following optimisation: remove dependencies from some test to reduce package time
