### ISSUE TITLE
[Getting Started] Example for creating customer with account

### ISSUE THREAD

**Issue by artur-barsegyan** [tarantool/cartridge-cli#121]
Today we don't have an example of HTTP request in GS, where we create a customer with account.
It's a problem because the users can't use `update_balance` API without an account. 

## Solution:
- create a customer with one default account
- add block with description of the `customer` structure (point on account field)

**Comment by dokshina** [comment]
See #271

**Comment by LeonidVas** [comment]
@artur-barsegyan  Do I understand correctly that the information you are interested in did not appear in the documentation?
I didn't find it, but maybe I missed something

**Comment by artur-barsegyan** [comment]
> @artur-barsegyan Do I understand correctly that the information you are interested in did not appear in the documentation? I didn't find it, but maybe I missed something

So, that Getting started is outdated. I don't have thoughts about what we are should do with it.

But if we talk about the case, the current Getting started in the documentation has the section about setting up an HTTP route for API function. [Maybe it's not general purpose but it has.](https://www.tarantool.io/ru/doc/latest/getting_started/getting_started_imcp/#setting-up-http-api-2-minutes)
