### ISSUE TITLE
Mention about dependencies for luarocks way of installation

### ISSUE THREAD

**Issue by artur-barsegyan** [tarantool/cartridge-cli#153]
By the current README, I can't install `cartridge-cli` via tarantoolctl.
After `tarantool` installation, I need some other dependencies like:
- tarantool-devel
- git
- cmake
and etc.

We need to mention it in the section.

**Comment by knazarov** [comment]
I suggest to create a release rock and specify in README the command that mentions a specific version. It will remove the neccessity to install additional dependencies.

For cartridge-based apps, I also suggest to implement #154 . It will make the whole developer experience better for newcomers.

**Comment by artur-barsegyan** [comment]
Yes, release rock actually resolve this issue. 

I have created [the ticket](https://github.com/tarantool/tarantool/issues/4793) about the installation of a last tagged version of a package in `tarantoolctl` by default. Wait for your comments.
