### ISSUE TITLE
Split cartridge-cli into several files

### ISSUE THREAD

**Issue by olegrok** [tarantool/cartridge-cli#181]
This project use "cmake" as a build system. This give us a huge possibilities to manipulate the source code files on the build stage. When we say about packages and usage it's quite good to have one file - one entrypoint, one script, etc.

However it's awful for developers and reviewers. My suggestion is to implement cmake script that will do following logic. On the build stage we read all files and then merge them into one:

```
package.loaded["1"] = load([[
-- the source code of the first module
]])

...

package.loaded["N"] = load([[
-- the source code of the Nth module
]])

-- Code of cartridge-cli.lua
local module1 = require('1') -- it's already added to package.loaded
...
```

**Comment by olegrok** [comment]
Closed in https://github.com/tarantool/cartridge-cli/commit/2097f959b4ec14001b267c3413119179c4b34b82

**Comment by olegrok** [comment]
There are some directions for improvements

**Comment by dokshina** [comment]
There is no directions - it's already rewritten in Go...
