### ISSUE TITLE
tarantoolctl rocks make failed

### ISSUE THREAD

**Issue by seet61** [tarantool/cartridge-cli#19]
I'm trying to do https://github.com/tarantool/cartridge-cli/blob/master/examples/getting-started-app/README_RUS.md.

`[root@esb-wso2-tst-01 getting-started-app]# tarantoolctl rocks make
Missing dependencies for getting-started-app scm-1:
   cartridge == 1.0.0-1 (not installed)

getting-started-app scm-1 depends on cartridge == 1.0.0-1 (not installed)
Installing http://rocks.tarantool.org/cartridge-1.0.0-1.all.rock
Missing dependencies for cartridge 1.0.0-1:
   http == 1.0.5-1 (not installed)
   lulpeg == 0.1.2-1 (not installed)
   errors == 2.1.1-1 (not installed)
   vshard == 0.1.9-1 (not installed)
   membership == 2.1.4-1 (not installed)
   frontend-core == 6.0.1-1 (not installed)

cartridge 1.0.0-1 depends on http == 1.0.5-1 (not installed)
Installing http://rocks.tarantool.org/http-1.0.5-1.rockspec

Error: Failed installing dependency: http://rocks.tarantool.org/cartridge-1.0.0-1.all.rock - Failed installing dependency: http://rocks.tarantool.org/http-1.0.5-1.rockspec - Could not find header file for TARANTOOL
  No file tarantool/module.h in /usr/local/include
  No file tarantool/module.h in /usr/include
You may have to install TARANTOOL in your system and/or pass TARANTOOL_DIR or TARANTOOL_INCDIR to the luarocks command.
Example: luarocks install http TARANTOOL_DIR=/usr/local`

But tarantool already installed by this instruction https://www.tarantool.io/ru/download/os-installation/1.10/rhel-centos-6-7/
`[root@esb-wso2-tst-01 getting-started-app]# tarantool -v
Tarantool 1.10.3-136-gc3c087d
Target: Linux-x86_64-RelWithDebInfo
Build options: cmake . -DCMAKE_INSTALL_PREFIX=/usr -DENABLE_BACKTRACE=ON
Compiler: /opt/rh/devtoolset-6/root/usr/bin/cc /opt/rh/devtoolset-6/root/usr/bin/c++
C_FLAGS:-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic  -fexceptions -funwind-tables -fno-omit-frame-pointer -fno-stack-protector -fno-common -fopenmp -msse2 -std=c11 -Wall -Wextra -Wno-strict-aliasing -Wno-char-subscripts -Wno-format-truncation -fno-gnu89-inline -Wno-cast-function-type
CXX_FLAGS:-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic  -fexceptions -funwind-tables -fno-omit-frame-pointer -fno-stack-protector -fno-common -fopenmp -msse2 -std=c++11 -Wall -Wextra -Wno-strict-aliasing -Wno-char-subscripts -Wno-format-truncation -Wno-invalid-offsetof -Wno-cast-function-type
`

OS info:
`[root@esb-wso2-tst-01 getting-started-app]# cat /etc/centos-release
CentOS Linux release 7.6.1810 (Core)
`

**Comment by RunsFor** [comment]
You need to install tarantool header files with `tarantool-devel` package:

```bash
sudo yum install -y tarantool-devel
```

**Comment by seet61** [comment]
Thanks, it help me. Please add mandatory dependencies to read.me: git, gcc, cmake. I think it will be very useful.

**Comment by RunsFor** [comment]
Great! I see you have been created an issue already #22. Closing this one then.
