### ISSUE TITLE
Missing RPM tags

### ISSUE THREAD

**Issue by Lebensgefahr** [tarantool/cartridge-cli#199]
Would you be so kind to add some additional RPM tags to align RPMs packages produced by cartridge-cli with the native builded RPMs. This will prevent errors in rpm processing of third party software like mc, genpkglist (altlinux repo tools) etc. Packages builded with the native rpmbuild are not causing this kind of errors
Why don't you use rpmbuild for rpm packages building? For example it strips debuginfo symbols from ELF files you are not stipping, it can use xz or gzip for different size files you can't.
Missing SOURCERPM tag causes non error exit code of genpkglist so it is not possible to create the repository with packages builded by cartridge-cli.
Bear in mind that missing of some tags in rpm spec file causes non error exit code of rpmbuild. You can use rpmlint to check produced rpm.
And please add the BuildArch for the package name.

**Comment by dokshina** [comment]
See #197
