### ISSUE TITLE
Read.me add information.

### ISSUE THREAD

**Issue by seet61** [tarantool/cartridge-cli#22]
Please add to readme information:
1. Mandatory dependencies: tarantool-devel, git, gcc, cmake.
2. To start shard correctly, you must click the Bootstrap button in the administrator interface.
3. Add information about admin password for UI.
4. For api.lua missing:
`local errors = require('errors')`
`local err_vshard_router = errors.new_class("Vshard routing error")`
`local err_httpd = errors.new_class("httpd error")`

**Comment by artur-barsegyan** [comment]
About the fourth: if you clone this repo and will try to do it again -> you get the result. It's all about incorrect README which misleading you, and you started to create files by youself. Right?

Repository contains other needed files for start.
