### ISSUE TITLE
Consider OS specific postfix for package name. 

### ISSUE THREAD

**Issue by filonenko-mikhail** [tarantool/cartridge-cli#23]
There is no crosscompilation, and rpm is unworkable at linux systems, if made from macos if and only if it contains compiled extensions.

**Comment by knazarov** [comment]
rpm made from OS X doesn't work on Linux if and only if it contains compiled extensions. 

for tar.gz I'd probably agree that we need a suffix

**Comment by filonenko-mikhail** [comment]
fixed description

**Comment by olegrok** [comment]
I think this commit resolves your issue - https://github.com/tarantool/cartridge-cli/commit/fe123e102e7ad69d6baf2afee7569109935d8e4c

You could specify e.g. `--suffix macos`

**Comment by Totktonada** [comment]
Is theer anything more expected from the cli? Autodetermination of the suffix (based on the build system)?

**Comment by filonenko-mikhail** [comment]
The thing is done, thanks a lot.
