### ISSUE TITLE
Create gitlab-ci job for uploading packages on download.tarantool.org repo

### ISSUE THREAD

**Issue by artembo** [tarantool/cartridge-cli#231]
Add gitlab ci job to manually upload distributives to download.tarantool.org repository

**Comment by artembo** [comment]
After last gitlab-ci update (12.10) I can't use AWS_SECRET_ACCESS_KEY and AWS_ACCESS_KEY_ID environment variables due to validation failure caused by the new gitlab validation
https://docs.gitlab.com/ee/ci/variables/#custom-variables-validated-by-gitlab.  
Workaround: AWS_ACCESS_KEY_ID=$ACCESS_KEY_ID

**Comment by dokshina** [comment]
Closed via #234
