### ISSUE TITLE
The tests from "Getting Started" are fails

### ISSUE THREAD

**Issue by artur-barsegyan** [tarantool/cartridge-cli#30]
At now, I am seeing the next error, when the tests failed:
```
Failed tests:
-------------
1) integration_api.test_transaction_chain
...amples/getting-started-app/test/integration/api_test.lua:24: expected: 201, actual: 404
stack traceback:
	...amples/getting-started-app/test/integration/api_test.lua:24: in function 'assert_http_json_request'
	...amples/getting-started-app/test/integration/api_test.lua:75: in function 'integration_api.test_transaction_chain'

Ran 2 tests in 0.004 seconds, 1 success, 1 failure
```

The reason is `cluster.main_server`, which actually doesn't point to `api` node in cluster. 
After my a little discovering, I am founded out that [the cartridge test helper](https://github.com/tarantool/cartridge/blob/master/cartridge/test-helpers/cluster.lua#L115) set up as the main server, any server which only one in own replicaset. (In my case it was `storage` server)

In general case, it's wrong.

**Comment by printercu** [comment]
Should be fixed in master. `make test-getting-started` is part of `test` task which runs on ci. Closing?
