### ISSUE TITLE
pack rpm should respect rpm naming rules

### ISSUE THREAD

**Issue by olegrok** [tarantool/cartridge-cli#303]
`[name]-[version]-[release].[arch].rpm`

https://www.thegeekdiary.com/understanding-rpm-versions-and-naming-schemes/

**Comment by mRrvz** [comment]
At the moment, only `arch` is missing in the naming, and basically all package names fit the rules described above. Maybe add `arch` for `tar.gz` and `deb` packages as well?

**Comment by olegrok** [comment]
> At the moment, only `arch` is missing in the naming, and basically all package names fit the rules described above. Maybe add `arch` for `tar.gz` and `deb` packages as well?

About deb - https://www.debian.org/doc/manuals/debian-reference/ch02.en.html#_debian_package_file_names
About tar.gz I'm not sure... If it's not really needed I'd skip such changes. Some customers use hardcoded patterns for their CIs.
