### ISSUE TITLE
[2pt] Command to wipe a data dir of the specified instance

### ISSUE THREAD

**Issue by Kasen** [tarantool/cartridge-cli#316]
I need to delete data of one instance, not of the entire cluster, sometimes. I can do it with bash, but it's not so convenient as the command execution.

**Comment by dokshina** [comment]
What do you think about `cartridge clean [INSTANCE_NAME...]`?

Should it delete everything? I mean instance workdir, log, pid file and sockets?

**Comment by Kasen** [comment]
I think this is a good idea. Yep, I think, it should delete everything.
