### ISSUE TITLE
UX: Quickstart is not going smoothly

### ISSUE THREAD

**Issue by RunsFor** [tarantool/cartridge-cli#320]
I ran into issues, repeating simple Quickstart script from the readme:

```bash
cartridge create --name myapp
cd myapp
cartridge build
cartridge start
```

1. When installing cartridge-cli on mac using homebrew, the tool assumes `/var/run/tarantool` with proper user permission is already exists. Hence, `cartridge start` fails. Fixed by manually creating `/var/run/tarantool`:

```
LuajitError: /Users/i.konyuhov/Workspace/testcartridge/myapp/init.lua:41: CartridgeCfgError: builtin/box/console.lua:833: failed to create server unix/:/var/run/tarantool/myapp.router.sock: No such file or directory
```

2. After `cartridge start` in web UI, when adding a second replica set, user will get the following error. Adding `workdir` option to `instances.yml` helped:
```
 SaveConfigError: /Users/i.konyuhov/Workspace/testcartridge/myapp/config.prepare: Directory not empty
```

I suggest to make Quickstart script work from scratch for any user even those with no knowledge of tarantool.

**Comment by dokshina** [comment]
Please, attach the result of `cartridge version` (or `cartridge --version`) to issue.

**Comment by RunsFor** [comment]
Thanks. It turned out, `cartridge` executable was dispatched from the wrong bundle (version 1.4.2). With 2.1.0 version everything seems to be fine. Besides it may be worthwhile to detect cartridge binary collision and warn the user that she has different cartridge installation already.

Closing this issue
