### ISSUE TITLE
Don't require the user to configure git

### ISSUE THREAD

**Issue by knazarov** [tarantool/cartridge-cli#366]
Currently we require the user to configure their git user/email when we create a project from template. It looks like this:

> Please tell me who you are.
> 
> Run
> 
>  git config --global user.email "you@example.com"
>. git config --global user.name "Your Name"

This is an issue for new users that just want to get started. I think we should make an initial commit from some sort of our internal user.

**Comment by Totktonada** [comment]
If you want my opinion, I would let a user to manage its project in any VCS (s)he want and avoid any git tweaks.

If we bother about backward compatibility here, okay, let's call `git commit --author 'Cartridge CLI <noreply@tarantool.org>'` or kinda. Looks quite easy to fix.

**Comment by LeonidVas** [comment]
I don't think we're going to do that.
