### ISSUE TITLE
Unable to interrupt cartridge build execution

### ISSUE THREAD

**Issue by vasiliy-t** [tarantool/cartridge-cli#369]
### Env:
macOS Mojave, 10.14.6
Tarantool Cartridge CLI v2.3.0 darwin/amd64 commit: 06a5dad

### Steps to repoduce:

1. run ```cartridge build```

2. hit ctrl + C to trigger interrupt

3. ```build``` continues running until finish

**Comment by mRrvz** [comment]
Checked for CLI 2.10.0 - everything is fine. Is the problem still relevant? @vasiliy-t

**Comment by vasiliy-t** [comment]
it works now
