### ISSUE TITLE
bootstrap cluster on start cmd

### ISSUE THREAD

**Issue by vasiliy-t** [tarantool/cartridge-cli#374]
`cartridge start` only starts instances.
It would be cool to extend `start` to automagically bootstrap cluster, set instance roles and upload cfg. Will save lot of time in dev env.

**Comment by vasiliy-t** [comment]
Didn't know about this option. Not working in 2.3

**Comment by dokshina** [comment]
Look at https://github.com/tarantool/cartridge-cli/blob/master/doc/replicasets.rst#setup-replica-sets-described-in-a-file.

Is it what you need?

**Comment by vasiliy-t** [comment]
Yep, this solves the issue
