### ISSUE TITLE
[13pt] Refactor Cartridge CLI documentation 

### ISSUE THREAD

**Issue by dokshina** [tarantool/cartridge-cli#375]
Now Cartridge CLI documentation is a huge and complicated. 
I think that it scares our new users.

My suggestion is to refactor current README to be a short description/example of basic Cartridge CLI usage.
The detailed description of commands and flags can be placed in separated topics (e.d like in [Cartridge](https://github.com/tarantool/cartridge/tree/master/rst) repo).

Moreover, we need to rework building in Docker description to be more simple.

**Comment by artur-barsegyan** [comment]
@dokshina still waiting for the new structure of README.

**Comment by veod32** [comment]
Current status: draft restructuring of Cartridge CLI doc is done in https://github.com/tarantool/cartridge-cli/pull/389

Remaining activities:
[ ] rebase https://github.com/tarantool/cartridge-cli/pull/389 -- @dokshina 
[ ] review the new structure -- doc team, product managers
[ ] review, edit and finalize the content -- doc team

**Comment by artur-barsegyan** [comment]
It is understood that this ticket will not improve the perception and navigation of the document.

Splitting into separate pages will entail incorrect links from the documentation, as well as a new way of assembling README for a section in the documentation.

**Comment by NickVolynkin** [comment]
From https://github.com/tarantool/doc/issues/1818:

> <…>f the «run-dir»
> parameter in the Cartridge configuration file).
> **|--data-dir DIR is |the** directory where instances“ data is stored.
> Each instance’s w<…>

https://www.tarantool.io/ru/doc/latest/book/cartridge/cartridge_cli/#overriding-default-options

Неактуальный параметр:
(carj=2.1.2, tnt=2.6.2)
source ./SDK/tarantool-enterprise/env.sh && \
cartridge stop --name ufm --verbose --cfg ./instances.yml --run-dir ./_local_workdir/run-dir/ --data-dir ./_local_workdir
Error: unknown flag: --data-dir
Usage:
...............
   ⨯ unknown flag: --data-dir

**Comment by NickVolynkin** [comment]
Resolved by https://github.com/tarantool/cartridge-cli/pull/634 and https://github.com/tarantool/doc/pull/2352
