### ISSUE TITLE
Topology management options (add role, add node to replicaset, etc)

### ISSUE THREAD

**Issue by akudiyar** [tarantool/cartridge-cli#376]
In addition to the admin API proposal by Vasiliy T (https://github.com/tarantool/cartridge-cli/issues/322#issue-666202975):

There should be a CLI alternative to configuring the cluster topology, the current API is a bit low-level and not easy to remember, and have no help or examples. For example, what functions should one call for changing the set of roles on a replica set? It will require logging into a router instance and executing a bunch of commands like

```lua
    cartridge = require('cartridge')
    replicasets = {{
        alias = 'app-router',
        roles = {'vshard-router', 'app.roles.custom', 'app.roles.api_router'},
        join_servers = {{uri = 'localhost:3301'}},
    }}
    cartridge.admin_edit_topology({replicasets = replicasets})`
```

And if there is a need for changing roles on several clusters, these actions should be repeated in each one.

A CLI alternative can be more comfortable for admin users:

`cartridge topology role-add "app.roles.api_router" --replicasets="app-router,hot,cold"`

`cartridge topology role-remove "app.roles.api_router" --global`

`cartridge topology replicaset-add "hot" --nodes "locahost:3311,localhost:3312"`

**Comment by dokshina** [comment]
See #396
