### ISSUE TITLE
[2pt] rpm deps: please add parameters to handle external dependencies

### ISSUE THREAD

**Issue by filonenko-mikhail** [tarantool/cartridge-cli#488]
There are cases when carg application uses some database connector. Database connector uses system database client library.

For e.g.

- postgresql connector uses libpq.so (from postgresq-libs)
- odbc connector uses postgresql-odbc
- etc

Could you please add extending rpm deps section for such cases?

**Comment by seet61** [comment]
Good idea. I have same problem after add gis at new project on cartridge.

**Comment by mRrvz** [comment]
## RFC

I suggest to add two options to ``cartridge pack`` command:

* ``--deps`` <slice>
* ``--deps-file``

For example:

```
cartridge pack rpm --deps dep01>=2,<3
cartridge pack rpm --deps dep02>=2 --deps dep02 < 3
cartridge pack rpm --deps-file depfile.txt
```

### Dependencies file format

Each line of file can be one of:

* ``<dependency-name> <relation> <version>``
* ``<dependency-name> <relation> <version>, <relation> <version>``

This format is not sensitive to spaces. Relations can be one of:

* ``=``
* ``==``
* ``>=``
* ``>``
* ``<``
* ``<=``

Order in which relations are deiscribed is not important:

```
dependency_01>=1,<2
dependency_02<2,>=1
```

Version can have as many ``.`` as you want:

* 2
* 2.5
* 2.5.1
* 2.5.4.1

File example: 

```
dependency_01 >= 2.5
dependency_01 < 4
dependency_02>=1,<5
dependency_03==2
dependency_04<5, >=1.5
```

### Additional notes

* If user specify ``--deps`` or ``--deps.txt``, and choose not ``RPM`` and not ``DEB``, we ignore flags and show warning.
* If user specify ``--deps`` and ``--deps.txt`` at the same time, we combine dependencies, **but not checking the repetitions and contradictions** (**or we need this check?**)
* We will **not check contradictions**, for example ``dependency01>=2.3,<1`` or ``dependency02==2.3,>5`` is correct (**or we need this check?**)
* In other cases, if at parsing stage we get an error, we stop working and show error to user.
