### ISSUE TITLE
admin: example on how to pack cartridge binary with tgz

### ISSUE THREAD

**Issue by opomuc** [tarantool/cartridge-cli#492]
Suppose I create a tar.gz with my project inside.

Currently I can't create a standalone installation, because neither `tarantool` binary nor `cartridge` are packed alongside the projcet. I propose adding instructions on how to add `cartridge` binary to tar.gz

Simple. In `cartridge.pre-build` file
```
#!/usr/bin/env bash

cp `which cartridge` .
```

**Comment by sharonovd** [comment]
I'd also add cli binary to tgz by default

**Comment by opomuc** [comment]
Cartridge cli больше не является стандартным инструментом
