### ISSUE TITLE
cartridge create app rockspec mixes space and tab indentation

### ISSUE THREAD

**Issue by DifferentialOrange** [tarantool/cartridge-cli#532]
Rockspec file of an app created with `cartridge create` command uses both spaces and tabs for indentation:

![image](https://user-images.githubusercontent.com/20455996/114388394-4b921380-9b9c-11eb-92b2-689770802dde.png)

**Comment by dokshina** [comment]
This was fixed in new versions (since 2.7.0 or earlier).

**Comment by DifferentialOrange** [comment]
> This was fixed in new versions (since 2.7.0 or earlier).

I've tried cli 2.7.2 and looks like it was fixed, but partially

![image](https://user-images.githubusercontent.com/20455996/114542215-57dfa480-9c60-11eb-97e4-4d019c91e746.png)
