### ISSUE TITLE
readline shortcuts not working and results in error

### ISSUE THREAD

**Issue by vasiliy-t** [tarantool/cartridge-cli#591]
### Problem statement 

I use readline commands for navigating my command history in bash. That is Ctrl + P for previous, Ctrl + N for next. Those shortcuts not working while being connected to instance via `cartridge connect` and results in error. 

### Steps to reproduce

1. connect to instance:
    `cartridge connect login:password@host:port`

2. type several commands
3. execute Ctrl + P shortcut
4. get no previous command
5. hit Enter twice:
![image](https://user-images.githubusercontent.com/4940266/126073547-187e3b78-74c2-426d-83f9-99d80dc320f9.png)

**Comment by mRrvz** [comment]
Tried to reproduce this on MacOS (in container too: docker for mac and centos:7 image), failed to reproduce

**Comment by Totktonada** [comment]
No feedback for 8 months, so I guess that the issue is not actual anymore. If the problem still exists, feel free to reopen the issue with details that would help us to reproduce it.
