### ISSUE TITLE
Describe local test run

### ISSUE THREAD

**Issue by DifferentialOrange** [tarantool/cartridge-cli#658]
There are no descriptions or prepared scripts (like make-commands) for test run. Setting up test environment requires using mage -- it is not a default `go mod tidy; go test .` run and not obvious for one unfamiliar with mage. Running a sequence of commands from CI was not enough for me: it failed with
```bash
Running unit tests...
../generate_templates_vfs.go:9:2: no required module provides package github.com/shurcooL/vfsgen; to add it:
	go get github.com/shurcooL/vfsgen
cli/codegen/static/static.go:5: running "go": exit status 1
Error: running "go generate -tags=dev ./cli/codegen/static" failed with exit code 1
```

**Comment by mRrvz** [comment]
About this error: it should disappear after #637.
