### ISSUE TITLE
pack docker error on M1

### ISSUE THREAD

**Issue by SWSAmor** [tarantool/cartridge-cli#694]
I run through the Cartridge doc step-by-step and everything was flawless until I tried
_cartridge pack docker_
then I got

```
Retrieving key from https://download.tarantool.org/tarantool/modules/gpgkey
Importing GPG key 0xA795CA3A:
 Userid     : "Tarantool <support@tarantool.io>"
 Fingerprint: 6acf 26a9 2e4e d97c 8bb9 0d45 ef12 8e21 a795 ca3a
 From       : https://download.tarantool.org/tarantool/modules/gpgkey
No package tarantool-devel available.
Error: Nothing to do

   ⨯ Failed to build base image: Build failed: The command '/bin/sh -c curl -L https://tarantool.io/installer.sh | VER=2.8 bash -s -- --type release     && yum -y install tarantool-devel' returned a non-zero code: 1

```
can you help me in this?
I'm on M1 Mac Mini with Homebrew and default Cartridge config only one helloworld.lua in app/roles.

**Comment by Totktonada** [comment]
We started preliminary support of ARM64 since tarantool 2.10.0-beta1. The 2.8 repository just have no packages for ARM64.

**Comment by SWSAmor** [comment]
Should I create a new app with cartridge-cli on Intel and move my lua files there to solve this?

**Comment by SWSAmor** [comment]
Thank you for the solution, cartridge pack docker ran successfully. 
I will test the created container on the weekend.

**Comment by Totktonada** [comment]
> For now we have no options to control tarantool version in the docker image for a cartridge app (we have `--deps` / `--deps-file` for RPM/Deb). However it would be good to implement it.

It is tracked in #88.

**Comment by kyukhin** [comment]
Closing, this is not an issue.

**Comment by Totktonada** [comment]
> I will test the created container on the weekend.

Okay. Please, close the issue if there will be no more problems.

If you want to debug a problem, which is not necessary a bug, it may be more profitable to join the chat: https://t.me/tarantool.

**Comment by Totktonada** [comment]
@SWSAmor Are there any updates?

**Comment by Totktonada** [comment]
@SWSAmor Feel free to re-open if you'll have something to add here. I'm going to close the issue as answered question.

**Comment by siller174** [comment]
any news?
