### ISSUE TITLE
Sometimes get errors on cartridge cli different commands - Failed to dial

### ISSUE THREAD

**Issue by byx01** [tarantool/cartridge-cli#697]
Hi, i'm newbe to tarantool, tried to install default cluster from docs with myapp. During configuration and after configuration the cluster I sometimes get errors "*Failed to dial*" on different cli commands. My config is on el8 , on 2 different hosts on same net.
cartridge version 
  Tarantool Cartridge CLI
   Version:       2.12.0
   OS/Arch:       linux/amd64
   Git commit:    b4ed1a2
 Tarantool Cartridge
   Version:       2.7.3-1

During config get errors on different commands , but entering same commands again same time everything goes OK. No errors in instance logs during commands. 
Examples of sometimes failed commands while getting "Failed to dial: dial unix /var/lib/tarantool/myapp/tmp/run/myapp.***.control: connect" :
   cartridge replicasets join --replicaset s-1 s1-master s1-replica
   cartridge replicasets add-roles   --replicaset router vshard-router app.roles.custom failover-coordinator metrics  
   cartridge replicasets list
Make some small test (see logs, hide IP by xxx) 
[cartridge_cli_github.log](https://github.com/tarantool/cartridge-cli/files/8452115/cartridge_cli_github.log)

**Comment by Totktonada** [comment]
Whether Unix domain socket path is less or equal 107 symbols (103 for Mac OS) at whole?

**Comment by Totktonada** [comment]
Ouch, sorry, I see it logs. It is less than 103/107.

**Comment by Totktonada** [comment]
Logs look like the `s2-master` instance unable to start. I need logs from it to investigate further.

**Comment by byx01** [comment]
> Logs look like the `s2-master` instance unable to start. I need logs from it to investigate further.
[s2_master.log](https://github.com/tarantool/cartridge-cli/files/8488833/s2_master.log)
[cartridge_command.log](https://github.com/tarantool/cartridge-cli/files/8488834/cartridge_command.log)
make test again, no errors or smth else in log on `s2-master` happen during when get erorrs on commands. I can connect to `s2-master` also without problems:
```

tarantool@x.x.x.83$ cartridge status
   • myapp-stateboard: NOT STARTED
   • myapp.router: NOT STARTED
   • myapp.router2: NOT STARTED
   • myapp.s1-master: NOT STARTED
   • myapp.s1-replica: RUNNING
   • myapp.s2-master: RUNNING
   • myapp.s2-replica: NOT STARTED

tarantool@x.x.x.83$ cartridge enter s2-master           
connected to myapp.s2-master
myapp.s2-master>
```

ps: I also added `router2`  for my another tests, think it doesn't depend on this issue.

**Comment by Totktonada** [comment]
I can't say much here and asked colleagues to take a look. We'll return here within this/next week.

**Comment by filonenko-mikhail** [comment]
Could you please attach logs from instances
- x.x.x.83:4303
- x.x.x.81:4303

**Comment by byx01** [comment]
> Could you please attach logs from instances
> 
> * x.x.x.83:4303
> * x.x.x.81:4303
I think it was about 83:4303 and 65:4303, see logs:
[x.x.x.65_4303_s2_replica.log](https://github.com/tarantool/cartridge-cli/files/8496247/x.x.x.65_4303_s2_replica.log)
[x.x.x.83_4303_s1_replica.log](https://github.com/tarantool/cartridge-cli/files/8496248/x.x.x.83_4303_s1_replica.log)

**Comment by psergee** [comment]
Suppose the issue is due to ConnectToSomeJoinedInstance function, which tries to connect to the console socket of some joined instance to get replicasets topology. But not all instances are running on local system, so cartridge cli fails to find the socket locally. Working on fix.
