### ISSUE TITLE
Cartridge-cli don't install on Ubuntu 22.04

### ISSUE THREAD

**Issue by swapper9** [tarantool/cartridge-cli#700]
This repository installation don't work:
curl -L https://tarantool.io/installer.sh | sudo -E bash -s -- --repo-only

If manually add jammy release to installer.sh, have:
E: The repository 'https://download.tarantool.org/DIjUyAN/tarantool/release/2.8/ubuntu jammy Release' does not have a Release file.
E: The repository 'https://download.tarantool.org/tarantool/modules/ubuntu jammy Release' does not have a Release file.

**Comment by Totktonada** [comment]
Waiting for tarantool packages for the new Ubuntu.

**Comment by Totktonada** [comment]
Tarantool packages are ready now. The time for cartridge-cli.
