### ISSUE TITLE
Pack docker raises not found error

### ISSUE THREAD

**Issue by rwegrzyniak** [tarantool/cartridge-cli#702]
I'm trying to pack newly created cartridge app with docker but when I run `cartridge pack docker` it throws errors:
```
https://download.tarantool.org/tarantool/release/series-2/el/7/x86_64/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found
Trying other mirror.


failure: repodata/repomd.xml from tarantool_2: [Errno 256] No more mirrors to try.
https://download.tarantool.org/tarantool/release/series-2/el/7/x86_64/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found
```

I'm using this guide https://www.tarantool.io/en/doc/latest/book/cartridge/cartridge_kubernetes_guide/#creating-an-application

**Comment by Totktonada** [comment]
What is your cartridge-cli version and tarantool version on the host system?

**Comment by rwegrzyniak** [comment]
cartridge-cli version 2.12.0
tarantool-cartridge version 2.7.3-1
tarantool version 2.9.0

**Comment by Totktonada** [comment]
2.9.0 is the technical release — start of 2.9 series, which later was [transformed](https://github.com/tarantool/tarantool/discussions/6182) to series-2 (2.10, 2.11, ...).

I suggest to update to [2.10.0-rc1](https://github.com/tarantool/tarantool/releases/tag/2.10.0-rc1). You can find installation instructions on [this page](https://www.tarantool.io/en/download/).

The original problem with 2.9.0 will gone with 2.10.0 release, which is planned on May/June.

I would consider this problem as a low priority task and would not work on it, considering that we have a workaround and that the problem will gone with the next tarantool release.

Please, let me know, whether the workaround (installation of 2.10.0-rc1) works for you.

**Comment by Totktonada** [comment]
Feel free to reopen if you have more inputs or if I misunderstood something.
