### ISSUE TITLE
Incorrect instructions in Cartridge docs

### ISSUE THREAD

**Issue by kluevandrew** [tarantool/cartridge-cli#708]
**Product:** Cartridge
**Since:** ?
**Root document:** https://www.tarantool.io/ru/doc/latest/book/cartridge/cartridge_dev/#starting-stopping-instances
**SME:** @ filonenko-mikhail 

# Details

Examples from doc page about Cartridge project creation lead to errors:

In docs:

<img width="1056" alt="Снимок экрана 2022-05-25 в 16 53 37" src="https://user-images.githubusercontent.com/2962993/170280286-69773f70-e687-404e-87f8-38b6525dc66f.png">

In real life:

<img width="933" alt="Снимок экрана 2022-05-25 в 16 55 31" src="https://user-images.githubusercontent.com/2962993/170280391-6af7fdb5-19f5-4555-bd9a-6bf537ded881.png">
<img width="761" alt="Снимок экрана 2022-05-25 в 16 55 42" src="https://user-images.githubusercontent.com/2962993/170280395-9fdd242d-1581-4309-b526-922c1bd50e4c.png">

---------

In docs:

<img width="1049" alt="Снимок экрана 2022-05-25 в 17 00 23" src="https://user-images.githubusercontent.com/2962993/170280606-5840d052-d5cb-4f57-aa38-4732b20acade.png">

In real life:

<img width="676" alt="Снимок экрана 2022-05-25 в 17 01 36" src="https://user-images.githubusercontent.com/2962993/170280845-db448be1-1489-478d-bc28-b3320f9094e2.png">

We need to check and update that page 
https://www.tarantool.io/ru/doc/latest/book/cartridge/cartridge_dev/#starting-stopping-instances

The [cartridge start reference](https://www.tarantool.io/ru/doc/latest/book/cartridge/cartridge_cli/commands/start/)
can be used as a source.

# Definition of done

* [ ] The instruction is correct: a user can execute it and get the expected result with no issues.

**Comment by p7nov** [comment]
* `--run_dir` seems to be a typo. There must be a hyphen instead of the underscore: `--run-dir`
* `--foreground` is not listed in `cartridge start --help`. Need to figure out the replacement. Perhaps `-d`/`--daemonize`` has something to do with it.
