### ISSUE TITLE
Provide ability to add Git hash in package file name

### ISSUE THREAD

**Issue by savinov** [tarantool/cartridge-cli#712]
cartride-cli doesn't add git hash in package name anymore after this PR: https://github.com/tarantool/cartridge-cli/pull/604#issuecomment-1003052367
Please provide cartridge-cli flag to return this feature.

**Comment by Totktonada** [comment]
Will not `--filename` option (#703, released in 2.12.1) suit you?

**Comment by savinov** [comment]
This solution works as cartridge-cli before PR:
`cartridge pack tgz --version $(git describe --tags --long)`
