### ISSUE TITLE
`cartridge pack docker` doesn't work

### ISSUE THREAD

**Issue by ramil-bitrise** [tarantool/cartridge-cli#792]
[Here](https://github.com/tarantool/cartridge-cli/blob/master/cli/project/dockerfiles.go#L297) outdated URL is hardcoded. And since yesterday it returns 500 error, so `cartridge pack docker` doesn't work completely.

**Comment by better0fdead** [comment]
Hi, for me this link works, are you sure that it is outdated, i have not found info about it.

**Comment by DifferentialOrange** [comment]
AFAIK, this link has been down for a couple days and then it was restored. @ylobankov may provide more info.

**Comment by ramil-bitrise** [comment]
Oh yes, just in the chat someone fairly replied that this link is not mentioned on the website anymore. This link is now everywhere: https://tarantool.io/release/2/installer.sh (version is specified in URL, same is available for v1 and v3). Also, no one seemed to be concerned about old link to be not working, that's why I decided that common `installer.sh` link is outdated.

**Comment by DifferentialOrange** [comment]
It still may be a good idea to migrate to the new link.
