### ISSUE TITLE
Strange behaviour when packaging cartridge with different versions of Tarantool

### ISSUE THREAD

**Issue by bm0** [tarantool/cartridge-cli#87]
Depending on the version of Tarantool on the machine where the cartridge will be packaged, a broken artifact may be obtained.

My research has shown that for some reason something is going on with the catalog `./rocks/share/tarantool/cartridge` inside the packed cartridge.

I made an example that shows how to reproduce the problem https://github.com/bm0/cartridge

**Comment by olegrok** [comment]
Thanks for your report

It seems that root of problem is https://github.com/tarantool/tarantool/issues/4704

**Comment by bm0** [comment]
@olegrok Thanks for feedback.
Do you know how soon it can be fixed?
We're worried because there are problems in production and we can't update our cartridge app.

**Comment by olegrok** [comment]
IMO, never

If you use 2.1, please upgrade to 2.2, because 2.1 is not supported more

If you use 1.10, you can use as workaround installation directly from rockspec - `tarantoolctl rocks install http://rocks.tarantool.org/cartridge-1.2.0-1.rockspec` - add it as hook into your build script

**Comment by olegrok** [comment]
Seems issue tarantool/tarantool#4704 is resolved. Now strange behaviour should disappear.

**Comment by olegrok** [comment]
I suggest to close this issue

**Comment by bm0** [comment]
@olegrok Thanks to all your team members!
